import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Bot, Loader, BrainCircuit, Sparkles, FileText, Download, Play } from 'lucide-react';
import api from '../../services/api';

const AuditorAISummary = () => {
  const [loading, setLoading] = useState(false);
  const [summaryData, setSummaryData] = useState('');
  const [hasRun, setHasRun] = useState(false);

  const fetchAI = async () => {
    setLoading(true);
    setHasRun(true);
    try {
      const res = await api.get('/auditor/ai-summary');
      setSummaryData(res.data);
    } catch (err) {
      console.error(err);
      setSummaryData('AI analysis is currently unavailable or failed to generate. Please check Gemini API configurations in the backend.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4 }}
      className="max-w-4xl mx-auto"
    >
      <div className="mb-8 flex flex-col sm:flex-row justify-between items-start sm:items-center">
        <div>
          <h1 className="text-2xl font-bold text-slate-800 flex items-center gap-2">
            <Sparkles className="text-blue-600" size={24} /> Automated Risk Intelligence
          </h1>
          <p className="text-slate-500 mt-1">Generated by Google Gemini 2.5 Flash analysis models.</p>
        </div>
        <button disabled={loading || !hasRun} className="mt-4 sm:mt-0 px-4 py-2 bg-white border border-slate-200 text-slate-600 rounded-lg shadow-sm hover:bg-slate-50 font-medium flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed">
          <Download size={18} /> Export PDF
        </button>
      </div>

      <div className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden relative">
        <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-blue-500 to-indigo-500"></div>
        
        <div className="p-8">
          <div className="flex items-center gap-4 mb-8">
            <div className="w-12 h-12 bg-blue-50 text-blue-600 rounded-xl flex items-center justify-center shrink-0 border border-blue-100 shadow-sm">
              <BrainCircuit size={28} />
            </div>
            <div>
              <h2 className="text-lg font-bold text-slate-800">System State Briefing</h2>
              <p className="text-slate-500 text-sm">Last snapshot: {hasRun ? new Date().toLocaleString() : 'Pending Generation'}</p>
            </div>
            <div className={`ml-auto px-3 py-1 rounded-full text-xs font-bold border ${!hasRun ? 'bg-slate-50 text-slate-500 border-slate-200' : (loading ? 'bg-yellow-50 text-yellow-700 border-yellow-200' : 'bg-green-50 text-green-700 border-green-200')}`}>
              {!hasRun ? 'NOT STARTED' : (loading ? 'PENDING' : 'ANALYSIS COMPLETE')}
            </div>
          </div>

          <div className="prose prose-slate max-w-none">
            {!hasRun ? (
               <div className="flex flex-col items-center justify-center space-y-6 py-12 bg-slate-50 rounded-xl border border-dashed border-slate-300">
                  <Bot size={48} className="text-blue-500 opacity-80" />
                  <div className="text-center">
                    <h3 className="text-lg font-semibold text-slate-700">Ready to Analyze Ledger</h3>
                    <p className="text-sm text-slate-500 mt-1 max-w-sm mx-auto">Click the button below to parse ledger transactions through Google Gemini 2.5 Flash constraints and identify anomalous behaviors.</p>
                  </div>
                  <button 
                     onClick={fetchAI}
                     className="px-6 py-3 bg-[var(--color-primary)] hover:bg-[#153457] text-white rounded-xl shadow-md transition-all font-medium flex items-center gap-2"
                  >
                     <Play size={18} /> Generate AI Intelligence Report
                  </button>
               </div>
            ) : loading ? (
              <div className="flex flex-col items-center justify-center space-y-4 py-12">
                <Loader className="animate-spin text-blue-600" size={32} />
                <p className="text-slate-500 animate-pulse">Gemini 2.5 Flash is actively parsing ledger transactions...</p>
              </div>
            ) : (
                <div className="bg-slate-50 border border-slate-200 p-6 rounded-xl font-medium text-slate-700 whitespace-pre-wrap leading-relaxed shadow-inner">
                  {summaryData}
                  
                  <div className="mt-8 pt-6 border-t border-slate-200 flex justify-center">
                    <button 
                       onClick={fetchAI}
                       className="px-5 py-2.5 bg-white border border-slate-300 hover:bg-slate-50 text-slate-700 rounded-lg shadow-sm transition-all text-sm font-medium flex items-center gap-2"
                    >
                       <Play size={16} /> Regenerate Report
                    </button>
                  </div>
                </div>
            )}
          </div>
        </div>

        <div className="bg-slate-50 border-t border-slate-200 p-4 px-8 text-sm text-slate-500 flex items-center justify-between">
          <span className="flex items-center gap-1"><ShieldCheck size={16} /> Data analyzed securely via SSL</span>
          <span>Model: Gemini-2.5-Flash</span>
        </div>
      </div>
    </motion.div>
  );
};

// Simple import inclusion for the footer
import { ShieldCheck } from 'lucide-react';

export default AuditorAISummary;
